added ESM module support
YunYouJun/mirai-ts pull request #45
Opened 2021-11-28 15:12 UTC by CaoMeiYouRen

添加了rollup ，用于支持 esm 模块，这个改动较大，需要再测试下。

我估计下面的代码应该是不需要的了，rollup已经添加了相应的内容。
``` ts
/**
 * mirai-ts 默认导出内容
 * @packageDocumentation
 */
// 必须放在最前面，适配 js require
if (typeof window === "undefined" && typeof module !== "undefined") {
    module.exports = Mirai;
    module.exports.default = Mirai;
    module.exports.Mirai = Mirai;
    exports = module.exports;
}
```

 api-extractor，用于打包 d.ts 文件。由于 "export * as ___"  语法不被支持所以稍加修改。
``` diff
- export * as check from "./utils/check";
- export * as template from "./utils/template";
+ import * as check from "./utils/check";
+ import * as template from "./utils/template";
+ export { check, template };
```

2021-11-29 11:31 UTC, YunYouJun approved these changes

2021-11-29 11:31 UTC, YunYouJun commented on package.json
> +    "build": "rimraf dist && rollup -c",
`rimraf` for windows?

2021-11-29 11:32 UTC, YunYouJun commented
事实上，我并未使用过 `api-extractor`，能否描述一下使用它的优势所在？

2021-11-29 13:11 UTC, CaoMeiYouRen commented on package.json
> +    "build": "rimraf dist && rollup -c",
采用 rimraf 可以支持 windows 开发

2021-11-29 13:12 UTC, CaoMeiYouRen commented
> 事实上，我并未使用过 `api-extractor`，能否描述一下使用它的优势所在？

要说优势的话，就是把类型文件打包成一个 index.d.ts 文件，减少了不必要的类型导出

2021-12-01 11:54 UTC, Samarium150 requested changes
用`npm link`实验了一下
- `chalk 5.0.0`还是会报错，不过在上一个pr已经解决了，`ts-node`可以正常跑
- 使用`api-extractor`后虽然只有一个`index.d.ts`文件，但是在WebStorm的代码类型提示变得稀烂，所有的import都得进这个文件用搜索找，不知道是什么原因。而且有一些类型甚至不知道怎么import，比如`NewFriendRequestOperationType`，`isAt`函数等等。

2021-12-01 12:06 UTC, CaoMeiYouRen commented
> 用`npm link`实验了一下
> 
> * `chalk 5.0.0`还是会报错，不过在上一个pr已经解决了，`ts-node`可以正常跑
> * 使用`api-extractor`后虽然只有一个`index.d.ts`文件，但是在WebStorm的代码类型提示变得稀烂，所有的import都得进这个文件用搜索找，不知道是什么原因。而且有一些类型甚至不知道怎么import，比如`NewFriendRequestOperationType`，`isAt`函数等等。

1. WebStorm的代码类型提示 问题我确实不太清楚，因为我是用 vscode 的，我也不清楚怎么回事。
2. 第二个问题我想可以解决。
2.1 `NewFriendRequestOperationType` 是 mirai-ts 内部 helper，本就不应该导出【检查了下代码，确实没有导出】
2.2 导出 `isAt`函数 的例子如下
```ts
import { check } from './index'
const { isAt } = check
```

2021-12-01 12:17 UTC, CaoMeiYouRen commented on package.json
> +    "@rollup/plugin-typescript": "^8.3.0",
添加 `@microsoft/api-extractor` 、`rollup` 等依赖

2021-12-01 12:18 UTC, CaoMeiYouRen commented on rollup.config.js
> +import { defineConfig } from "rollup";
添加 rollup 配置文件

2021-12-01 12:18 UTC, CaoMeiYouRen commented on tsconfig.json
> +    "target": "es2018",
修改 `target` 目标，保守一点的话改成 `es2015` 或许更加合理

2021-12-01 12:35 UTC, YunYouJun commented on rollup.config.js
> +  // {
注释部分我们还需要吗？ESM 应该是 browser 也可以用的吧。

2021-12-01 12:35 UTC, YunYouJun commented on rollup.config.js
> +      target: "es2018",
已经传入 tsconfig,json，此处应该不用设置 `module` 和 `target` 等了？

> https://github.com/rollup/plugins/tree/master/packages/typescript/#tsconfig

2021-12-01 12:36 UTC, Samarium150 commented
- 之前我直接用了`import { BotInvitedJoinGroupRequestOperationType, NewFriendRequestOperationType } from "mirai-ts/dist/mirai-api-http/resp";`
- 代码提示我再研究一下，看看能不能解决

2021-12-01 12:40 UTC, CaoMeiYouRen commented on rollup.config.js
> +      target: "es2018",
应该是不需要了，这里会覆盖 `tsconfig.json`。

2021-12-01 12:43 UTC, CaoMeiYouRen commented on rollup.config.js
> +  // {
> 
1. 注释部分删了吧，无所谓。 
2. 可以的。由于 `event` 模块并没有连带着打包出来，所以 browser 环境下只要另外安装 `event` 模块就行。【跟之前一样】

2021-12-01 12:44 UTC, CaoMeiYouRen commented
> * 之前我直接用了`import { BotInvitedJoinGroupRequestOperationType, NewFriendRequestOperationType } from "mirai-ts/dist/mirai-api-http/resp";`
> * 代码提示我再研究一下，看看能不能解决

- 由于只有一个 `index.d.ts` 文件了，所以没有子目录了，全都从 "mirai-ts" 导出

2021-12-01 12:47 UTC, Samarium150 commented
> * 由于只有一个 `index.d.ts` 文件了，所以没有子目录了，全都从 "mirai-ts" 导出
```typescript
mirai.on("NewFriendRequestEvent", (request) => {
        // void request.respond(NewFriendRequestOperationType.Accept);
        void request.respond(0);
});
```
但自释性变差了，还得加注释

2021-12-01 12:50 UTC, CaoMeiYouRen commented
> > * 由于只有一个 `index.d.ts` 文件了，所以没有子目录了，全都从 "mirai-ts" 导出
> 
> ```ts
> mirai.on("NewFriendRequestEvent", (request) => {
>     // void request.respond(NewFriendRequestOperationType.Accept);
>     void request.respond(0);
> });
> ```
> 
> 但自释性变差了，还得加注释

这个不是 rollup 的问题，是项目本身没有导出，你应该要求项目导出这个类型

2021-12-01 13:18 UTC, Samarium150 commented
@CaoMeiYouRen 那么想用`MessageChain`的话是
```typescript
import { MessageType } from "mirai-ts";
type MessageChain = MessageType.MessageChain;
```
这样吗

2021-12-01 13:21 UTC, CaoMeiYouRen commented
> @CaoMeiYouRen 那么想用`MessageChain`的话是
> 
> ```ts
> import { MessageType } from "mirai-ts";
> type MessageChain = MessageType.MessageChain;
> ```
> 
> 这样吗

- 对的

2021-12-01 13:33 UTC, YunYouJun commented
> > > * 由于只有一个 `index.d.ts` 文件了，所以没有子目录了，全都从 "mirai-ts" 导出
> > 
> > 
> > ```ts
> > mirai.on("NewFriendRequestEvent", (request) => {
> >     // void request.respond(NewFriendRequestOperationType.Accept);
> >     void request.respond(0);
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但自释性变差了，还得加注释
> 
> 这个不是 api-extractor 的问题，是项目本身没有导出，你应该要求项目导出这个类型

这些相关类型是有导出的。

![image](https://user-images.githubusercontent.com/25154432/144243118-97f944c2-7e9d-4646-a92b-15cf68b17fb6.png)

![image](https://user-images.githubusercontent.com/25154432/144243197-d5af8983-b7be-4ce2-b201-6274ec88ec94.png)

现在是把所有类型都从 mirai-ts 到出对吧。

2021-12-01 13:35 UTC, Samarium150 reviewed
推测可能是WebStorm对link的库支持不太好，等deploy了再看看有没有问题

2021-12-01 13:35 UTC, Samarium150 commented on package.json
>    "version": "2.1.1",
增加一下版本号？当前应该是`2.1.2`

2021-12-01 13:37 UTC, Samarium150 commented
> 现在是把所有类型都从 mirai-ts 到出对吧。
对，用`api-extractor`的话所有类型都在`index.d.ts`中导出

2021-12-01 13:40 UTC, Samarium150 approved these changes

2021-12-01 13:42 UTC, CaoMeiYouRen commented
`src\helper.ts` 没有在 `src\index.ts` 导出

从 Windows 版邮件发送

发件人: 云游君
发送时间: 2021年12月1日 21:33
收件人: YunYouJun/mirai-ts
抄送: CaoMeiYouRen; Mention
主题: Re: [YunYouJun/mirai-ts] ✨ added ESM module support (PR #45)

• 由于只有一个 index.d.ts 文件了，所以没有子目录了，全都从 "mirai-ts" 导出
mirai.on("NewFriendRequestEvent", (request) => {

    // void request.respond(NewFriendRequestOperationType.Accept);

    void request.respond(0);

});
但自释性变差了，还得加注释
这个不是 api-extractor 的问题，是项目本身没有导出，你应该要求项目导出这个类型
这些相关类型是有导出的。


现在是把所有类型都从 mirai-ts 到出对吧。
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

2021-12-01 13:45 UTC, CaoMeiYouRen commented
> > > > * 由于只有一个 `index.d.ts` 文件了，所以没有子目录了，全都从 "mirai-ts" 导出
> > > 
> > > 
> > > ```ts
> > > mirai.on("NewFriendRequestEvent", (request) => {
> > >     // void request.respond(NewFriendRequestOperationType.Accept);
> > >     void request.respond(0);
> > > });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 但自释性变差了，还得加注释
> > 
> > 
> > 这个不是 api-extractor 的问题，是项目本身没有导出，你应该要求项目导出这个类型
> 
> 这些相关类型是有导出的。
> 
> ![image](https://user-images.githubusercontent.com/25154432/144243118-97f944c2-7e9d-4646-a92b-15cf68b17fb6.png)
> 
> ![image](https://user-images.githubusercontent.com/25154432/144243197-d5af8983-b7be-4ce2-b201-6274ec88ec94.png)
> 
> 现在是把所有类型都从 mirai-ts 到出对吧。

`src\helper.ts` 没有在 `src\index.ts` 导出

2021-12-07 10:55 UTC, YunYouJun commented
> src\helper.ts 没有在 src\index.ts 导出

helper.ts 里只有一个函数 `createHelperForMsg`，内部使用，不需要导出。

2021-12-07 11:05 UTC, CaoMeiYouRen commented
> > src\helper.ts 没有在 src\index.ts 导出
> 
> helper.ts 里只有一个函数 `createHelperForMsg`，内部使用，不需要导出。

所以说 `NewFriendRequestOperationType` 没有从 `src\index.ts` 导出，自然不会出现在 `dist\index.d.ts` 文件里

2021-12-07 11:06 UTC, YunYouJun commented
我查看了下目前新增的内容，但是感觉配置上可能增加了维护成本。

使用 tsup https://github.com/egoist/tsup，是否会更好？

请问是否有别的看法？

2021-12-07 11:15 UTC, CaoMeiYouRen commented
> 我查看了下目前新增的内容，但是感觉配置上可能增加了维护成本。
> 
> 使用 tsup https://github.com/egoist/tsup ，是否会更好？
> 
> 请问是否有别的看法？

 - tsup 没有使用过，所以没法给意见。

 - 我想还是得重新评估下这次改动的目标，是实现 esm 支持还是其他的。我的想法是简化 dist 产物，减少 dist 文件夹体积，顺带实现 esm。

2021-12-07 16:48 UTC, YunYouJun commented
Refactor with [tsup](https://github.com/egoist/tsup). More info see https://github.com/YunYouJun/mirai-ts/pull/46.

Thanks for your PR. I will close it. How about create a new PR to add `temp` for it?

2021-12-07 16:48 UTC, closed without merging