:bug: fix route path of command system, add missed command event.
YunYouJun/mirai-ts pull request #50
Opened 2022-07-06 08:47 UTC by NFWSA

想要尝试一下command相关的接口，发现现在的支持有问题
根据 https://github.com/project-mirai/mirai-api-http/blob/master/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/adapter/internal/consts/paths.kt 
mirai-api-http的comand的接口路由现在是cmd开始，下面有cmd/register和cmd/execute，修改于15个月前
而mirai-ts的实现中，相关接口仍然写的是command/register和command/send，所以修复了路由，同时把Command.send接口名字也改成了Command.execute保证一致
另外EventMap中缺乏CommandExecute事件，导致mirai-api-http转发的接口调用事件没法直接监听，所以补上了这部分。

2022-07-06 12:08 UTC, YunYouJun requested changes

2022-07-06 12:08 UTC, YunYouJun commented on src/types/event-type.ts
> +  * 命令名称
需要 lint 成这种形式

```js
/**
 *
 */
```

2022-07-07 03:34 UTC, NFWSA commented on src/types/event-type.ts
> +  * 命令名称
修好了

2022-07-07 14:35 UTC, merged

2022-07-07 14:55 UTC, YunYouJun commented
Released in `v2.4.0`.

Could you test it?

2022-07-08 02:38 UTC, NFWSA commented
```typescript
// file command-test.ts
// ...

async function app() {
    await mirai.link(qq);
    mirai.on('message', (msg) => {
        // eslint-disable-next-line no-console
        // console.log(msg)
    });

    mirai.api.command.register("test", ['command', 'alias'], 'test command interface', 'test <args>...');
    mirai.on("CommandExecutedEvent", (data) => {
        if (data.name == 'test' || data.name == 'command' || data.name == 'alias') {
            console.log(data);
            if (data.friend != null) {
                mirai.api.sendFriendMessage(data.args, data.friend.id);
            }
            else if (data.member != null) {
                mirai.api.sendGroupMessage(data.args, data.member.group.id);
            }
            else {
                mirai.logger.debug(data.args);
            }
        }
    });
    mirai.listen();
}

app();
```
yeah, here is my test code and runtime result is below:
```bash
# ./mcl --boot-only
## after run ts-node command-test.ts
> help
# ...
◆ test <args>...
## result for send friend message:
2022-07-08 09:59:13 V/Bot.*********: Event: net.mamoe.mirai.api.http.command.CommandExecutedEvent@46b5fda1
2022-07-08 09:59:13 V/Bot.*********: 杯弓蛇影(*********) -> #test qq friend cmd test
2022-07-08 09:59:13 V/Bot.*********: Friend(*********) <- qqfriendcmdtest
## result for send group member message:
2022-07-08 09:59:37 V/Bot.*********: [Test(*********)] 测试名(*********) -> #test qq member cmd test
2022-07-08 09:59:37 V/Bot.*********: Event: net.mamoe.mirai.api.http.command.CommandExecutedEvent@c7e430e
2022-07-08 09:59:38 V/Bot.*********: Group(*********) <- qqmembercmdtest
## result for console command:
> test 123 456 test
2022-07-08 09:59:50 V/Bot.*********: Event: net.mamoe.mirai.api.http.command.CommandExecutedEvent@66a92375
```
```bash
# yarn upgrade
yarn upgrade v1.22.19
warning package.json: No license field
warning No license field
warning No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
warning No license field
success Saved 62 new dependencies.
info Direct dependencies
├─ @types/js-yaml@4.0.5
├─ @types/jsdom@16.2.14
├─ @types/node@18.0.3
├─ fs@0.0.1-security
├─ js-yaml@4.1.0
├─ jsdom@20.0.0
└─ mirai-ts@2.4.0
...

# ts-node command-test.ts 
[mirai-api-http] [info] [http] Address: http://localhost:8080
[mirai-api-http] [info] [http] Session: itmOgxPM
[mirai-api-http] [success] 验证成功
[mirai-api-http] [info] [websocket] [all](消息与事件) ws://localhost:8080
[mirai-api-http] [info] [ws] Session: NnnVOlAR
## result for send friend message:
{
  type: 'CommandExecutedEvent',
  name: 'test',
  friend: { id: 000000000, nickname: '杯弓蛇影', remark: '****' },
  member: null,
  args: [
    { type: 'Plain', text: 'qq' },
    { type: 'Plain', text: 'friend' },
    { type: 'Plain', text: 'cmd' },
    { type: 'Plain', text: 'test' }
  ],
  reply: [AsyncFunction (anonymous)]
}
## result for send group member message:
{
  type: 'CommandExecutedEvent',
  name: 'test',
  friend: null,
  member: {
    id: 000000000,
    memberName: '测试名',
    specialTitle: '',
    permission: 'OWNER',
    joinTimestamp: 1529044925,
    lastSpeakTimestamp: 1657245577,
    muteTimeRemaining: 0,
    group: { id: 000000000, name: 'Test', permission: 'MEMBER' }
  },
  args: [
    { type: 'Plain', text: 'qq' },
    { type: 'Plain', text: 'member' },
    { type: 'Plain', text: 'cmd' },
    { type: 'Plain', text: 'test' }
  ],
  reply: [AsyncFunction (anonymous)]
}
## result for console command:
{
  type: 'CommandExecutedEvent',
  name: 'test',
  friend: null,
  member: null,
  args: [
    { type: 'Plain', text: '123' },
    { type: 'Plain', text: '456' },
    { type: 'Plain', text: 'test' }
  ],
  reply: [AsyncFunction (anonymous)]
}
[mirai-api-http] [debug] [
  { type: 'Plain', text: '123' },
  { type: 'Plain', text: '456' },
  { type: 'Plain', text: 'test' }
]
```
so I think it works fine, if you needed, i can send runtime picture (I used text rather than image, beacuse there isn't suitable gallery website.

2022-07-08 13:19 UTC, YunYouJun commented
That's ok. Have fun!