fix: improve image typescript
YunYouJun/mirai-ts pull request #52
Opened 2022-10-09 07:16 UTC by hengkx

2022-10-09 16:59 UTC, YunYouJun approved these changes

2022-10-09 17:10 UTC, YunYouJun requested changes
想起来这么写好像是因为有个坑，mirai-api-http 不想设置值，必须字段存在然后传入 null。不然不传就是 undefined，那边校验就报错。

2022-10-10 02:22 UTC, hengkx commented
> 想起来这么写好像是因为有个坑，mirai-api-http 不想设置值，必须字段存在然后传入 null。不然不传就是 undefined，那边校验就报错。

不会啊，我之前写 没有传是可以 成功的

2022-10-10 05:49 UTC, hengkx commented
 有bug急着用 fork来用了

2022-10-10 05:49 UTC, closed without merging

2022-10-13 12:27 UTC, YunYouJun commented
现在会有啥 BUG？

2022-10-13 12:30 UTC, hengkx commented
> 现在会有啥 BUG？

消息撤回 有两个参数

2022-10-13 20:53 UTC, YunYouJun commented
应该是 mirai API 设计进行了更新，此前只需要一个参数。
之后更新。

2022-10-13 21:24 UTC, YunYouJun commented
> > 现在会有啥 BUG？
> 
> 消息撤回 有两个参数

Fixed in `v2.4.2`.